services:
  soflex-desktop:
    build:
      context: .
      dockerfile: Dockerfile
    image: soflex-desktop        # le da un nombre fijo a la imagen
    container_name: soflex1

    ports:
      - "5900:5900"              # VNC

    environment:
      # Arranque automático del script Python
      AUTO_START: "1"
      # Abrir también el browser al inicio (opcional)
      OPEN_URL: "https://youtube.com/@todonoticias/live"
      BROWSER: "firefox"         # firefox | chrome
      # Parámetros que tu app espera (url navegador ffmpeg|gstreamer)
      APP_ARGS: "https://youtube.com/@todonoticias/live firefox ffmpeg"

      # Forzar locale si XFCE se queja
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"

    volumes:
  # Montás tu repo (modo dev)
  # - ./:/home/soflex/Escritorio/Soflex/audio-automatizado-api-transcript:rw
  # - ./start.sh:/start.sh:ro

  # Logs y grabaciones persistentes fuera del contenedor
  # - ./_logs:/home/soflex/logs:rw
  # - ./_records:/home/soflex/Escritorio/Soflex/audio-automatizado-api-transcript/records:rw

  # Volúmenes para Windows (usar rutas absolutas)
    - C:/Users/David/Soflex/audio-automatizado-api-transcript:/home/soflex/Escritorio/Soflex/audio-automatizado-api-transcript:rw
    - C:/Users/David/Soflex/audio-automatizado-api-transcript/start.sh:/start.sh:ro
    - C:/Users/David/Soflex/audio-automatizado-api-transcript/_logs:/home/soflex/logs:rw
    - C:/Users/David/Soflex/audio-automatizado-api-transcript/_records:/home/soflex/Escritorio/Soflex/audio-automatizado-api-transcript/records:rw

    # Para Chrome/Firefox (evita glitches por /dev/shm chico)
    shm_size: "1gb"

    restart: unless-stopped
    tty: true

    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'Xvfb :0' >/dev/null && pgrep -f 'x11vnc .*:0' >/dev/null"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s
